### ISSUE TITLE
FixedArray of rank 1 fails to get its gradient

### ISSUE THREAD

**Issue by acriaer** [rjhogan/Adept-2#10]
Hello,
I found that the following code:
```C
    adept::Stack main_stack;
    adept::FixedArray<adept::Real, true, 2> v({2, 3});
    main_stack.new_recording();
    adept::aReal r = adept::sum(v); 

    r.set_gradient(1.0);
    main_stack.reverse();

    std::cerr << v.get_gradient();
```

throws at _v.get_gradient()_:
>terminate called after throwing an instance of 'adept::gradient_out_of_range'
>  what():  Gradient index out of range: probably aReal objects have been created after a set_gradient(s) call

If I substitute the first line with:
```C
adept::FixedArray<adept::Real, true, 2, 2> v({{2, 3}, {2, 3}});
```
then it all works well. 

Am I doing something wrong?
This happens to me on Linux both with GCC 5.4.0 and Clang 6.0.

**Comment by rjhogan** [comment]
Bug.  Latest commit should fix - please let me know.  Thanks!
