### ISSUE TITLE
_mm_undefined_ps missing on old clang

### ISSUE THREAD

**Issue by dougalsutherland** [rjhogan/Adept-2#7]
`Packet.h` [has test code](https://github.com/rjhogan/Adept-2/blob/5e1a1e913249b2bb8ed4d725121011b2a94be9a7/include/adept/Packet.h#L27-L36) to define `_mm_undefined_ps` if it's missing on old GCC. Old Clangs, though, also don't have this instruction, causing build failures: [example Travis failure](https://travis-ci.org/conda-forge/staged-recipes/builds/335253483#L458).

I was able to work around it in [the `conda-forge` package we're adding](https://github.com/conda-forge/staged-recipes/pull/5034) with [a dumb patch](https://github.com/dougalsutherland/staged-recipes/blob/0576bc852e5b8ad1731df91d0d37f82a34c8b413/recipes/adept/_mm_undefined_ps.patch), which I'm only applying for our OSX builds. You shouldn't put this in Adept, because it's incorrect (if `_mm_undefined_ps` is defined as a function rather than a macro, as it actually is, it'll override that definiton), but there should probably be a version check for clang too.

**Comment by rjhogan** [comment]
P {margin-top:0;margin-bottom:0;}


Thanks - yes I found this problem recently with clang and was planning to post a fix soon.
Regards,
Robin.

**Comment by yurivict** [comment]
Could you please fix this? I am seeing the same problem in the FreeBSD port in systems with older clang versions.

**Comment by rjhogan** [comment]
Should be fixed in latest push.

**Comment by yurivict** [comment]
Thanks! Please consider making a release because the port sources it from http://www.met.reading.ac.uk/clouds/adept/ which doesn't get latest pushes.

**Comment by rjhogan** [comment]
Will do on Monday hopefully - have one further issue to resolve and then need to test with a larger application before I can be sure it's ready for a release.

**Comment by yurivict** [comment]
Thanks!

**Comment by dougalsutherland** [comment]
Support for `_mm_undefined_ps` was added in clang 3.8, if you wanted to support it there too. (It was added in [this commit](https://github.com/llvm-mirror/clang/commit/85a91ffe2038db56dd1b2603255bbf051c712947), which via `git branch -a --contains 85a91ffe` is present on the `release_38` brach.)

**Comment by rjhogan** [comment]
I think it can be done with #if __has_builtin(__builtin_ia32_undef128)
This seems to work in the latest commit (only tested on Clang >= 3.8, not Clang < 3.8).

**Comment by rjhogan** [comment]
2.0.5 now released at http://www.met.reading.ac.uk/clouds/adept/

**Comment by yurivict** [comment]
Thanks!

**Comment by rjhogan** [comment]
With no reports to the contrary, I will assume that 2.0.5 fixes this issue
